# Redis Helm values for AKS demo
architecture: replication
auth:
  enabled: true
  password: "New1234!"
  existingSecret: ""
  existingSecretPasswordKey: ""

master:
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi
  
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi

replica:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi
  
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi

metrics:
  enabled: false

service:
  type: ClusterIP

# 네임스페이스 지정
global:
  namespaceOverride: "hyunwoo-hw"
